version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: seller_bot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seller_bot_db
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: seller_bot_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: seller_bot_app
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pg_data:
